[package]
name = "fan"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.2", features = ["derive"] }
libc = "0.2.153"
sysinfo = { version = "0.30.7", features = ["serde"] }
walkdir = "2.5.0"

[build-dependencies]
bindgen = "0.69.4"
cc = "1.0"
